[[Antlr4CppRuntime]]
arch = "aarch64"
git-tree-sha1 = "5e76aa81852f1ba31f76b4a2f784617417a5d50f"
os = "macos"

    [[Antlr4CppRuntime.download]]
    sha256 = "86d5b242e94ee6c85c9b6a4794e0542efa1c5ec77b8094a65285beb3eb179918"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.aarch64-apple-darwin.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4f484f4e04c043286be71fe845111abac635672"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "dbc1f8f57f773017394f9ff10a2de0dfebf9f4742f3e3d2c69fb0a14b7a325e9"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cb907ba212a4b1e62e06241a3985d9774e1c11b"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "9fc46ffd8a8c537584f3f8ecc4aceffc1f86e276aa8de76e879bd278ba13544f"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "536ae9d8ebbe58c575fe026e299107259a605ae2"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "eff78d1ca172f14568dad2f04a628f3fc9e075bb828bda295ada19cbf18b0c8e"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.aarch64-linux-musl-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "244765e184dc79efcecaacb5310d4b0b54aad909"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "ab3629a6b24ed946d33515390ea4eb61302274cab8c339e7723f9b0a3424725b"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.aarch64-linux-musl-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c805e7b1b02d26585f38c2101caaa059f011999"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "ed35f0a568481745da76dfc28f02790390bf22c87f0b9d8a5c9983839c51a53c"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56b6e90c8f4c51dac39256b91f2ffa2cf654bb66"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "8cc50365d3fda5c302f4a010357432f9c893f32b5d87230e0044acd47365a44d"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e51249fa8566fe950ba5c15b9129768820156f0b"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "1afe3511db33b7a4f8a2d0541cb27d728cdec8beaf807d44722a3de969a0c738"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d1c0cb36ed509f9ab19e36eaf3c67499e1ba449"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "cb40f027d5925b799d51bd4f8f944336c99b6e0d31813bd6aa1a9944f4ee07f5"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6041103bd0cac55a8432060a595c50a282f67e99"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "63f6118a618705ae4dfb184714e9d0a5bf0d31c05166e8883c0db705456885cf"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2526aaef0feffe8b9b475e2a5536a71255503bc"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "45d3bd7028ac64bf2e77d9c06a9058bd4cbbb3ce1a80bff0a998b6f11da79414"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e62cfec95a23c32327ae87ab4db4ea105ef89ffa"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "48d83100947306c48446b88f1fe45d211569dc64dfd109f7dcad08d64a50e180"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ec9010a97908739f19888d8b4dd8169cf84b629"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "8c3d7d98d487305e8be2aee21b98cdafdedef416d4235382fc38ed4e5cb08b35"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acc6b4d50067e3b86b53c28a7d7bde77cf4b7bd0"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "d3ce5d8f4fce3d32767aaa45dc9b4701ec2f4989d92f8b185f48947415dbe3e1"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.i686-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4acef2ee567be8e3396eab3076fc9ec7f3e21abd"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "a4993551d35d66df413efc2db988a7fee8206771efea32026188c74869b49b91"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.i686-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9daf456b70da632baa181d769e3ad101181cef1a"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "f47550ccc85f094fff05d51b8fb2b3ca6f0ef16a515a9e5d4a24b17542c61598"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.i686-linux-musl-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8b34615d9962a49beff834fcf6e9c7e07d32ca4"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "49d0d8f62d5a89490bc7ced8fd659ff69ccbcc6635b76111ab944a94b4aaf62a"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.i686-linux-musl-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdb30060b8ae427225e1df6d9a2f3b6f7d6bbc80"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "ee5404db35b53829651eb4d05e6f63dce74e839469c6fa8826a090f276331b56"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.i686-w64-mingw32-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20e33b04c690e6e7bfcc4dd61608610633623f1e"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "bcde1e21f6d4bfe64acd2c05fdd07c34fed0e53c80374ae8bfe220f05bf6203f"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.i686-w64-mingw32-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d757aa74af0f5f030aba872580554a0f03ae305a"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "0caf22c686a546915229515e69b97a42024da6e6e7897108c64c7802b6491193"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d055d1cf7d21223b80b49de8540872811a374dd"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "0177d8952dba989e46dab6e6dc6b79a7a354aacae20ccf06e72d8c20a59cbc42"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
git-tree-sha1 = "90cdf00f8af8acb64aa6d90f08f3020ca4eefd70"
os = "macos"

    [[Antlr4CppRuntime.download]]
    sha256 = "665a23c91f5dd9216c3955cc2faf32f26be63fc2f206fcbf7f12fb41d52fbe73"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-apple-darwin.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fd66956f5f5d667f74a70afd899793a1ec87cb1"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "de67c6c8ad1d5edec2f09826ad46dfb294cbb30cc0fa5ce6339aaf4c77554335"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "621e241709a94ea63345418b090da14f63c749de"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "45e5d26fe84634d994bf20f68cec306ba383d25c46eccb02dd48400c37ff09fb"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e42e774131daad02af9b8185deeb256de2a99812"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "e7049114506b4ca47d32f5cd2eeb32f9384f91ee845d225763b79e4996a826de"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-linux-musl-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ac8e41b2ed8348c35c1c302591b7e90b9fc20cf"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "ce997efdc2c550597c5adf5ced0c90ce20ea350a6f19631a351f175d4f8adb7b"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-linux-musl-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
git-tree-sha1 = "f12c6e7717256f89bead400fe6c3a6680e7d4d17"
os = "freebsd"

    [[Antlr4CppRuntime.download]]
    sha256 = "9e0fc8d5d69d4bec2280a696d6852ad8329df33de13078bb58883ce366a2446a"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-unknown-freebsd.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33cd90f71cb705ad44286efd47cb35af8dea8486"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "25caf1cb4b05c725d939482c679e86948051c3ecec643e767c79090d08c457c1"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae88d9324b336e3794c2ef89437c0a998dbdc62f"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "647d6cfd350db6033bf9f937eb52242733cba6ebb5196ff051c338455565b9a6"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+1/Antlr4CppRuntime.v4.9.3.x86_64-w64-mingw32-cxx11.tar.gz"
