[[Antlr4CppRuntime]]
arch = "aarch64"
git-tree-sha1 = "1fd3bf72739760c72a8d5c535b24f5b50db93321"
os = "macos"

    [[Antlr4CppRuntime.download]]
    sha256 = "f921b4a26b0cb886f1f68bf969790b8749a57b2c5c97eab7fc1276455f90c222"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.aarch64-apple-darwin.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b8f04fb6b7101ec188a379699a0eeaa668263ae"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "df9791326e241ffaee312bf6a43de9d8ec9c124c3fe5d8f0fe3e9b161858a51d"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a384934db6dee132548a2d0ccfd582774d7ef5bd"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "51f4e8cd4a0fb29f0868397c9e1e1c1338bbaba5dd0ea47a26424d6b7e28ab36"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5fd58fcc77af63736370c52d123eedae9b3c6535"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "c9f8827fad3b3d5d99754d52d430a7cb37363ff2e79bec6b5aedd2aecb4677b3"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.aarch64-linux-musl-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e4a78ae8aa6692a43573b9057e3a73b9fb7fc12"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "5f5d0e08bdab7375b43e9d271961e8415d4c15355a1dd08836466c5ec5d1315b"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.aarch64-linux-musl-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b224091944b8b3dd317ea71189785d5b0e8460a3"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "dd653e30a2332f8194cf0657fce0cca7485e1d575d72e6482164033b962530c2"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e916b746a8604310043e653678f30fb23f20a03b"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "70b2286083e02784d0bf92e0058ff0e3d70fa317a4584e8e598f9fd278e77b95"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e6c56186073389221e664a8c1d58001c106ab83"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "d50653633af78b88929b25821eb1e83a17052df1a09c5ad926be0d088b63b5b2"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3a1cb89d69bfeff8831205e9b12a7407b67c802"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "ac92b38a820a643cbd2e4a57908bf7e05819b7438a8480e18f84fbe2e1b76a0b"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f713086fdb3cf2dd1a595461379c5996c70893f0"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "fa7589b12b586ce17ea9997a18395a460a91038f9d31c825a1e8e89b02ba7652"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac4226dbf62e7f734613a2b9873959bc52266281"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "09e270c4c74459af5d03fb6a8d9a8236e4d43d1077a2cef2d8eae607c289e519"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abe4c7e1b9e41cd700dd343ad0f3b425a0dd6e45"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "227b17e65bc0f560e157fbcf21ba7bb9da68807db14aca64847f09a706f50957"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65b6107b1bbe58c9255bf2eec6e122fa2bf71372"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "26e64319668d4cb9b531bd6bdf39de46d58174c37fe4546899a09c947375e43c"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13e1a59226c0ad7a8af341e93fa83bb0430601d2"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "bc71b2d16b0d4e1f5a2e184c2db1303b48f78006dbfe881e2033d1576f5a57fc"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.i686-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ebc8d8a39b7909a948a4db80547e59ad4eeb016"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "f1a25ce76bceab0a5dd382d6884f513ab86abfc4c1c772de689f1a56f40ba5f1"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.i686-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e92a58e36bb083b83a66a6c79934a73222b04d7"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "f1a0b6cf2a87498c88e910a84f700e72986640c40197c752665f508898de26e7"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.i686-linux-musl-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6cf63df600a523b71c55b95809bfa30f43cb446"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "7a90efdc53eae8f7a60b6f7ebd39ec5d0dc18d5b98d13eefad90706124e28d19"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.i686-linux-musl-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3933ef8f7a8022be6e2bf7576ab2d1559f8882be"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "f010145cace4329158571d09d645681674baef66337d3f38513585f3d1afd8b3"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.i686-w64-mingw32-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "702125cb8e8a1749c5426c64a782badab78bcb8f"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "fb9ae834c201331d9d7ee0974fe28d64872ddba05a1c9c75bf7dd7b2590c387a"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.i686-w64-mingw32-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42bbc9c96c0db32610ffeade5fca96e0e3065d4b"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "b7334376f51fa27ecd9e63a74c4b7f744c2c2c4bbed7c41df6a853d201687e0a"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0711c957e9455c37ea83950197c98a11bc53862b"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "5b15af6f72b8deb28c23040c1f1dc8e4653fd4a60d7412412bcfab9423c29f43"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
git-tree-sha1 = "1cd07fcc0285c59a89cc0ad29f9195109a6cff88"
os = "macos"

    [[Antlr4CppRuntime.download]]
    sha256 = "3ce5af32813704e1f4dbd5699723b30ce08a9f47d193f26c30bfb04bc6ea43c1"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-apple-darwin.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "416757d4c3967ec8ed9bba87b888ed75b05f5365"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "2e75b044a7cd457cab05aab981ab93f98e7e5a9df44c1d202b7a1c0d7811a60e"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7c1fb6418d27d5c571e3568bf7b0b469ad26cde"
libc = "glibc"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "a44b58b0da1b2548f0998a34e82ec9f23587a2a82cf3d72b5aa83179c42c31b2"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de5e9c3c24373da67fdd799426d46f9c0a82d9c4"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "62f67d5046c460fa4b4825d1c926446c385cfb240451b620d9d8a5cee3821cf1"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-linux-musl-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11090c9f718410c86a86796e1fd5e762762ca7bd"
libc = "musl"
os = "linux"

    [[Antlr4CppRuntime.download]]
    sha256 = "d63bf0a9f24a564d3d47b75f2fc813190c2f828fcfb0d416175d1ca338ca3c81"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-linux-musl-cxx11.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
git-tree-sha1 = "3cfa4bee026a286647a6d3b42ec5a1e1d96c842e"
os = "freebsd"

    [[Antlr4CppRuntime.download]]
    sha256 = "818261d54491e70cf2349edf70d2984501c88a07060ff24215fdfbb7904d97e7"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-unknown-freebsd.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98c4c1596fe3e2dc19e3221ffe3be96603e26aef"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "1ce08c5293fc8a6627cf15ee8b4072bf7188bd3a93002dc82c859ab7e2a2414c"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Antlr4CppRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94cd71fc49c4ad25aa93385fc1bdc41ecdf6da36"
os = "windows"

    [[Antlr4CppRuntime.download]]
    sha256 = "472012b8eac485cb141ae547554b9357cb18e4f1b8ba33eb022584a4e33271c7"
    url = "https://github.com/JuliaBinaryWrappers/Antlr4CppRuntime_jll.jl/releases/download/Antlr4CppRuntime-v4.9.3+0/Antlr4CppRuntime.v4.9.3.x86_64-w64-mingw32-cxx11.tar.gz"
