# Autogenerated wrapper script for Antlr4CppRuntime_jll for x86_64-apple-darwin
export libantlr4_cpp_runtime

JLLWrappers.@generate_wrapper_header("Antlr4CppRuntime")
JLLWrappers.@declare_library_product(libantlr4_cpp_runtime, "@rpath/libantlr4-runtime.4.9.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libantlr4_cpp_runtime,
        "lib/libantlr4-runtime.4.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
